# This file was generated by GoReleaser. DO NOT EDIT.
cask "agentpaas" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "4b54b1d3bf9598115a486ec34a3a04f0bc3dc980f580b9523f099d4214613ac4"
      url "https://github.com/AgentPaaS-ai/agentpaas/releases/download/v#{version}/agentpaas_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "1cb627840f2bd9e1ccffb2c88c5adfde9945c4bf82d62369eaadd153ed6e93cd"
      url "https://github.com/AgentPaaS-ai/agentpaas/releases/download/v#{version}/agentpaas_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "agentpaas"
  desc "Governed, local-first runtime for AI-generated agents"
  homepage "https://github.com/AgentPaaS-ai/agentpaas"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "agentpaas"
  binary "agentpaasd"
  binary "agentpaas-harness-linux"
  binary "agentpaas-harness-linux-amd64"

  # No zap stanza required

end
