# This file was generated by GoReleaser. DO NOT EDIT.
cask "agentpaas" do
  depends_on :macos

  version "0.5.0"

  on_macos do
    on_intel do
      sha256 "ab0163e704797fa898d679f2b69235b2bffe9351365052102345825db5972074"
      url "https://github.com/AgentPaaS-ai/agentpaas/releases/download/v#{version}/agentpaas_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "3cb4db1a9c13302858493064ca357102e145bf995312f616a927d40161bfe3ce"
      url "https://github.com/AgentPaaS-ai/agentpaas/releases/download/v#{version}/agentpaas_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "agentpaas"
  desc "Governed, local-first runtime for AI-generated agents"
  homepage "https://github.com/AgentPaaS-ai/agentpaas"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "agentpaas"
  binary "agentpaasd"
  binary "agentpaas-mcp"
  binary "agentpaas-harness-linux"
  binary "agentpaas-harness-linux-amd64"

  postflight do
    if OS.mac?
      %w[agentpaas agentpaasd agentpaas-mcp agentpaas-harness-linux agentpaas-harness-linux-amd64].each do |name|
        system_command "/usr/bin/xattr", args: ["-cr", "#{staged_path}/#{name}"]
      end
    end
  end

  # No zap stanza required

end
