# This file was generated by GoReleaser. DO NOT EDIT.
cask "agentpaas" do
  version "0.2.3"

  on_macos do
    on_intel do
      sha256 "b55553df7d74b66970f0b8fef8cf8891fa5cbfb6d5b2a23776b5810baf9eda29"
      url "https://github.com/AgentPaaS-ai/agentpaas/releases/download/v#{version}/agentpaas_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "dbc93e57876e8c941abf799122674518a5a31c98f7363d6983ceff766bfa394a"
      url "https://github.com/AgentPaaS-ai/agentpaas/releases/download/v#{version}/agentpaas_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "agentpaas"
  desc "Governed, local-first runtime for AI-generated agents"
  homepage "https://github.com/AgentPaaS-ai/agentpaas"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "agentpaas"
  binary "agentpaasd"
  binary "agentpaas-harness-linux"

  # No zap stanza required

end
