# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Agentpaas < Formula
  desc "Governed, local-first runtime for AI-generated agents"
  homepage "https://github.com/AgentPaaS-ai/agentpaas"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AgentPaaS-ai/agentpaas/releases/download/v0.1.0/agentpaas_0.1.0_darwin_amd64.tar.gz"
      sha256 "c79f43b007465a8f5c95433e4d10638530124d1ae7d3be17f5cb3e90e1f66823"

      define_method(:install) do
        bin.install "agentpaas"
        bin.install "agentpaasd"
        bin.install "agentpaas-harness-linux"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AgentPaaS-ai/agentpaas/releases/download/v0.1.0/agentpaas_0.1.0_darwin_arm64.tar.gz"
      sha256 "6844693b73b1dd2793b087e18a41ff8aa46857fb9ff1984f1f4748517997e31d"

      define_method(:install) do
        bin.install "agentpaas"
        bin.install "agentpaasd"
        bin.install "agentpaas-harness-linux"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AgentPaaS-ai/agentpaas/releases/download/v0.1.0/agentpaas_0.1.0_linux_arm64.tar.gz"
      sha256 "587970188a02fd866b6bf3a31c9c47042ff81feae9a30a4b89ab658b25a3d8a3"
      define_method(:install) do
        bin.install "agentpaas"
        bin.install "agentpaasd"
        bin.install "agentpaas-harness-linux"
      end
    end
  end

  test do
    system "#{bin}/agentpaas", "version"
  end
end
