# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Agentpaas < Formula
  desc "Governed, local-first runtime for AI-generated agents"
  homepage "https://github.com/AgentPaaS-ai/agentpaas"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AgentPaaS-ai/agentpaas/releases/download/v0.1.0/agentpaas_0.1.0_darwin_amd64.tar.gz"
      sha256 "f38acfe83870a015207a3a3913d3f34800427fbcf206e3eda42cacc02c43bfc5"

      define_method(:install) do
        bin.install "agentpaas"
        bin.install "agentpaasd"
        bin.install "agentpaas-harness-linux"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AgentPaaS-ai/agentpaas/releases/download/v0.1.0/agentpaas_0.1.0_darwin_arm64.tar.gz"
      sha256 "9d32e9af38b0322a66a6e12aa945ee77cc93e337d02e9bda884a0922cb05efc6"

      define_method(:install) do
        bin.install "agentpaas"
        bin.install "agentpaasd"
        bin.install "agentpaas-harness-linux"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AgentPaaS-ai/agentpaas/releases/download/v0.1.0/agentpaas_0.1.0_linux_arm64.tar.gz"
      sha256 "7dddb495883ab438de245fad5ce466197928a7afc108ade2165da583b7798b9d"
      define_method(:install) do
        bin.install "agentpaas"
        bin.install "agentpaasd"
        bin.install "agentpaas-harness-linux"
      end
    end
  end

  test do
    system "#{bin}/agentpaas", "version"
  end
end
