# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Agentpaas < Formula
  desc "Governed, local-first runtime for AI-generated agents"
  homepage "https://github.com/AgentPaaS-ai/agentpaas"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AgentPaaS-ai/agentpaas/releases/download/v0.1.0/agentpaas_0.1.0_darwin_amd64.tar.gz"
      sha256 "42761048b8275ecbb63a83c6736afb51d815d9e68803b8ee0ebd528163761c82"

      define_method(:install) do
        bin.install "agent"
        bin.install "agentpaasd"
        bin.install "agentpaas-harness-linux"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AgentPaaS-ai/agentpaas/releases/download/v0.1.0/agentpaas_0.1.0_darwin_arm64.tar.gz"
      sha256 "6fa3f9eb86c0a5d52f2bf3e6c58691f3486014c648f7e039e8cab6934fb8aab8"

      define_method(:install) do
        bin.install "agent"
        bin.install "agentpaasd"
        bin.install "agentpaas-harness-linux"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AgentPaaS-ai/agentpaas/releases/download/v0.1.0/agentpaas_0.1.0_linux_arm64.tar.gz"
      sha256 "fdfff5f92700254df8f970d9c8a82f935fd98452f0644f5d9026247bd8c086f8"
      define_method(:install) do
        bin.install "agent"
        bin.install "agentpaasd"
        bin.install "agentpaas-harness-linux"
      end
    end
  end

  test do
    system "#{bin}/agent", "version"
  end
end
